version: '3'
services:
    web:
        image: nginx
        ports:
            - "8080:8080"
        networks:
            - frontend
    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: password
        networks:
            - backend
networks:
    frontend:
    backend: